# Generated by Django 3.2.12 on 2022-02-27 14:01

import django.core.validators
from django.db import migrations, models
import payments.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('street_and_number', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('postal_code', models.CharField(max_length=6, validators=[payments.models.Address.postal_code_validator])),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('payment_intent_id', models.CharField(blank=True, max_length=250)),
                ('payment_status', models.CharField(blank=True, max_length=50)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('amount', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(15)])),
                ('live_mode', models.BooleanField(null=True)),
            ],
        ),
    ]
