# Generated by Django 3.2.12 on 2022-02-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topup',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='topup',
            name='is_successful',
            field=models.BooleanField(default=False),
        ),
    ]
